kibot:
  version: 1

global:
  filters:
  - number: 1007
  - number: 1015
  - number: 58

outputs:
# MANUFACTURE ARTWORK
#JLCPCB outputs
- name: JLCPCB_gerbers
  comment: Gerbers compatible with JLCPCB
  type: gerber
  dir: Output/Manufacturers/JLCPCB
  options:
    exclude_edge_layer: true
    exclude_pads_from_silkscreen: true
    plot_sheet_reference: false
    plot_footprint_refs: true
    plot_footprint_values: false
    force_plot_invisible_refs_vals: false
    tent_vias: true
    use_protel_extensions: true
    create_gerber_job_file: false
    disable_aperture_macros: true
    gerber_precision: 4.6
    use_gerber_x2_attributes: false
    use_gerber_net_attributes: false
    line_width: 0.1
    subtract_mask_from_silk: true
    inner_extension_pattern: .gp%n
  layers: &id002
  - layer: F.Cu
    suffix: F_Cu
    description: Front copper
  - layer: B.Cu
    suffix: B_Cu
    description: Bottom copper
  - layer: F.Paste
    suffix: F_Paste
    description: Front solder paste
  - layer: B.Silkscreen
    suffix: B_Silkscreen
    description: Bottom silkscreen (artwork)
  - layer: F.Silkscreen
    suffix: F_Silkscreen
    description: Front silkscreen (artwork)
  - layer: B.Mask
    suffix: B_Mask
    description: Bottom soldermask (negative)
  - layer: F.Mask
    suffix: F_Mask
    description: Front soldermask (negative)
  - layer: Edge.Cuts
    suffix: Edge_Cuts
    description: Board shape
- name: JLCPCB_drill
  comment: Drill files compatible with JLCPCB
  type: excellon
  dir: Output/Manufacturers/JLCPCB
  options:
    pth_and_npth_single_file: false
    pth_id: -PTH
    npth_id: -NPTH
    metric_units: true
    map: gerber
    route_mode_for_oval_holes: false
    output: '%f%i.%x'
- name: JLCPCB
  comment: ZIP file for JLCPCB
  type: compress
  dir: Output/Manufacturers
  options:
    files:
    - from_output: JLCPCB_gerbers
      dest: /
    - from_output: JLCPCB_drill
      dest: /
# PCBWay outputs
- name: PCBWay_gerbers
  comment: Gerbers compatible with PCBWay
  type: gerber
  dir: Output/Manufacturers/PCBWay
  options: &gerber_options
    exclude_edge_layer: true
    exclude_pads_from_silkscreen: true
    plot_sheet_reference: false
    plot_footprint_refs: true
    plot_footprint_values: true
    force_plot_invisible_refs_vals: false
    tent_vias: true
    use_protel_extensions: true
    create_gerber_job_file: false
    output: "%f.%x"
    gerber_precision: 4.6
    use_gerber_x2_attributes: false
    use_gerber_net_attributes: false
    disable_aperture_macros: true
    line_width: 0.1
    subtract_mask_from_silk: false
    inner_extension_pattern: '.gl%N'
  layers:
    - copper
    - F.SilkS
    - B.SilkS
    - F.Mask
    - B.Mask
    - F.Paste
    - B.Paste
    - Edge.Cuts
- name: PCBWay_drill
  comment: Drill files compatible with PCBWay
  type: excellon
  dir: Output/Manufacturers/PCBWay
  options:
    metric_units: false
    minimal_header: true
    zeros_format: SUPPRESS_LEADING
    # left_digits: 3
    # right_digits: 3
    # See https://github.com/INTI-CMNB/kicad-ci-test-spora/issues/1
    # and https://docs.oshpark.com/design-tools/gerbv/fix-drill-format/
    left_digits: 2
    right_digits: 4
    pth_and_npth_single_file: false
    pth_id: ''
    npth_id: '-NPTH'
    output: "%f%i.drl"
- name: PCBWay
  comment: ZIP file for PCBWay
  type: compress
  dir: Output/Manufacturers
  options:
    format: ZIP
    files:
      - from_output: PCBWay_gerbers
        dest: /
      - from_output: PCBWay_drill
        dest: /

# BOM OUTPUTS
# BOMs in hand-place format (ibom), and generic CSV BOM.
- name: basic_ibom
  comment: Interactive HTML BoM
  type: ibom
  dir: Output/Assembly
  options:
    include_tracks: true
    dark_mode: true
- name: 'bom_csv'
  comment: "Bill of Materials in CSV format"
  type: bom
  dir: Output/Assembly

# DOCUMENTATION
# Basic design info first, schem & images.
- name: basic_pcbdraw_png_jlcpcb_green_hasl_top
  comment: PCB 2D render in PNG format, using jlcpcb-green-hasl style
  type: pcbdraw
  dir: Output
  options:
    style: jlcpcb-green-hasl
    format: png
- name: basic_pcbdraw_png_jlcpcb_green_hasl_bot
  comment: PCB 2D render in PNG format, using jlcpcb-green-hasl style
  type: pcbdraw
  dir: Output
  options:
    bottom: true
    style: jlcpcb-green-hasl
    format: png
- name: basic_pdf_sch_print
  comment: Schematic in PDF format
  type: pdf_sch_print
  dir: Output

# Diffs for both schem & PCB between current and last commit. Maybe change to KIBOT_TAG-n for "old" when releases working.
- name: basic_diff_pcb
  comment: PCB diff between the last two changes
  type: diff
  dir: Output/DiffChanges
  layers:
  - layer: F.Cu
    suffix: F_Cu
    description: Front copper
  - layer: B.Cu
    suffix: B_Cu
    description: Bottom copper
  - layer: B.Silkscreen
    suffix: B_Silkscreen
    description: Bottom silkscreen (artwork)
  - layer: F.Silkscreen
    suffix: F_Silkscreen
    description: Front silkscreen (artwork)
  - layer: Edge.Cuts
    suffix: Edge_Cuts
    description: Board shape
  options:
    old: HEAD~
    old_type: git
    new: HEAD
    new_type: git
    cache_dir: /mnt/sunriselamp/.cache
    add_link_id: true
    copy_instead_of_link: true
- name: basic_diff_sch
  comment: Schematic diff between the last two changes
  type: diff
  dir: Output/DiffChanges
  options:
    old: HEAD~
    old_type: git
    new: HEAD
    new_type: git
    cache_dir: /mnt/sunriselamp/.cache
    add_link_id: true
    copy_instead_of_link: true
    pcb: false
