name: example

on:
  push:
    paths:
      - 'Hardware/*.kicad_sch'
      - 'Hardware/*.kicad_pcb'
      - '**.kibot.yaml'
      - '**kibot.yml'
  pull_request:
    paths:
      - 'Hardware/*.kicad_sch'
      - 'Hardware/*.kicad_pcb'
      - '**.kibot.yaml'
      - '**kibot.yml'

jobs:
  quick:
    name: "Quick Start (action)"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: INTI-CMNB/KiBot@v2_k6
      with:
        quickstart: YES

    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: Automatic_outputs
        path: Generated